"""Write precache-manifest.js: every file the app needs to open and run offline, with a
content hash so the service worker only re-downloads files that changed.

    python islamhub/tools/build_precache.py

Also stamps sw.js with the manifest hash, so any content change ships a new worker.
Runs in the Pages deploy workflow too, so the manifest is always current.
Large data (city prayer tables, Qur'an page text, images, audio) is cached at runtime
or on explicit download instead of being forced on every visitor.
"""
import hashlib, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIRS = ["js", "css", "vendor"]
INCLUDE_FILES = ["index.html", "manifest.json", "assets/logo", "assets/icons"]
EXCLUDE = [
    re.compile(r"^js/data/jadwal/"),          # 66 cities x 1.6 MB: cached when a city is used
    re.compile(r"^js/data/alquran/pages/"),   # Qur'an page text: on demand / "Mode Offline"
    re.compile(r"^js/data/live-streams\.json$"),  # refreshed every 3 hours; network-first
    re.compile(r"^css/style\.css$"),          # legacy stylesheet, not loaded
    re.compile(r"^assets/icons/.*(_files/|\.html$|source\.png$)"),  # generator leftovers
    re.compile(r"^vendor/fontawesome/webfonts/.*\.ttf$"),  # woff2 is used everywhere we run
    re.compile(r"\.(md|py|map|txt)$"),
]
EXTS = {".html", ".js", ".mjs", ".css", ".json", ".woff2", ".ttf", ".png", ".webp", ".svg", ".ico", ".jpg", ".jpeg"}


def files():
    for d in INCLUDE_DIRS:
        yield from (p for p in (ROOT / d).rglob("*") if p.is_file())
    for f in INCLUDE_FILES:
        p = ROOT / f
        if p.is_dir():
            yield from (q for q in p.iterdir() if q.is_file())
        elif p.exists():
            yield p


def main():
    entries = {}
    for p in files():
        rel = p.relative_to(ROOT).as_posix()
        if p.suffix.lower() not in EXTS or any(r.search(rel) for r in EXCLUDE):
            continue
        entries[rel] = hashlib.sha1(p.read_bytes()).hexdigest()[:12]
    entries = dict(sorted(entries.items()))
    version = hashlib.sha1(json.dumps(entries).encode()).hexdigest()[:12]
    size = sum((ROOT / k).stat().st_size for k in entries)
    body = ("// GENERATED by tools/build_precache.py. Do not edit.\n"
            f"self.__PRECACHE_VERSION = '{version}';\n"
            f"self.__PRECACHE = {json.dumps(list(entries.items()), separators=(',', ':'))};\n")
    (ROOT / "precache-manifest.js").write_text(body, encoding="utf-8")
    sw = ROOT / "sw.js"
    text = sw.read_text(encoding="utf-8")
    sw.write_text(re.sub(r"const BUILD = '[^']*';", f"const BUILD = '{version}';", text), encoding="utf-8")
    print(f"{len(entries)} files, {size / 1048576:.1f} MB, version {version}")


if __name__ == "__main__":
    main()
