"""Self-host the Google Fonts used by IslamHub so the app renders offline (PWA and Capacitor).

    python islamhub/tools/vendor_fonts.py

Writes vendor/fonts/fonts.css and the woff2 files it references. Only Latin and Arabic
subsets are kept; other scripts are not used by the app.
"""
import hashlib, re, urllib.request
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "vendor" / "fonts"
FAMILIES = [
    "Orbitron:wght@400;500;600;700;900",
    "Rajdhani:wght@300;400;500;600;700",
    "Plus+Jakarta+Sans:wght@400;500;600;700;800",
    "Fraunces:opsz,wght@9..144,500;9..144,600",
    "Amiri:wght@400;700",
    "Amiri+Quran",
    "Scheherazade+New:wght@400;500;600;700",
    "Noto+Naskh+Arabic:wght@400;500;600;700",
]
KEEP = ("latin", "latin-ext", "arabic")
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60) as r:
        return r.read()


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    url = "https://fonts.googleapis.com/css2?" + "&".join(f"family={f}" for f in FAMILIES) + "&display=swap"
    css = get(url).decode("utf-8")
    blocks = re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
    out, n = [], 0
    for subset, block in blocks:
        if subset not in KEEP:
            continue
        src = re.search(r"url\((https://[^)]+)\)", block).group(1)
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        name = f"{fam.lower().replace(' ', '-')}-{subset}-{hashlib.sha1(src.encode()).hexdigest()[:8]}.woff2"
        path = OUT / name
        if not path.exists():
            path.write_bytes(get(src))
            n += 1
        out.append(f"/* {subset} */\n" + block.replace(src, name))
    (OUT / "fonts.css").write_text("/* Self-hosted Google Fonts, generated by tools/vendor_fonts.py */\n" + "\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(out)} faces, {n} new files")


if __name__ == "__main__":
    main()
